services:
  comfyui:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USER_UID=${USER_UID?USER_UID is required. Launch me with up.sh to set it automatically.}
        - USER_GID=${USER_GID?USER_GID is required. Launch me with up.sh to set it automatically.}
    volumes:
      - "confyenv:/home/comfy/.local"
      - "hfhub_cache:/home/comfy/.cache/huggingface"
      - "./workspace:/workspace"
    ports:
      - "10001:8188"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
  
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - "./workspace/ComfyUI/models:/srv/models"
      - "./workspace/ComfyUI/input:/srv/input"
      - "./workspace/ComfyUI/output:/srv/output"
      - "./workspace/filebrowser.db:/database.db"
    user: "${USER_UID}:${USER_GID}"
    ports:
      - "10002:80"
    depends_on:
      comfyui:
        condition: service_healthy

volumes:
  confyenv:
  hfhub_cache:
    external: true