services:
  comfyui:
    image: %BUILT_IMAGE%
    volumes:
      - "type=bind,src=/home/%USER_NAME%/.cache/huggingface/,dst=/home/%USER_NAME%/.cache/huggingface/"
      - "type=bind,src=/home/%USER_NAME%/.cache/uv/,dst=/home/%USER_NAME%/.cache/uv/"
      - "type=bind,src=/home/%USER_NAME%/.cache/torch/hub/,dst=/home/%USER_NAME%/.cache/torch/hub/"
      - "type=bind,src=%REPO_DIR%/scripts/,dst=/scripts/"
      - "type=bind,src=%REPO_DIR%/workspace/,dst=/workspace/"
    ports:
      - "10001:8188"
    command: ["bash", "/scripts/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "bash", "/scripts/healthcheck.sh"]
      interval: 60s
      timeout: 10s
      start_period: 30s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
  
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - "./workspace/ComfyUI/models:/srv/models"
      - "./workspace/ComfyUI/input:/srv/input"
      - "./workspace/ComfyUI/output:/srv/output"
      - "./workspace/filebrowser.db:/database.db"
    user: "%USER_UID%:%USER_GID%"
    ports:
      - "10000:80"
    depends_on:
      comfyui:
        condition: service_healthy
